/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.internal.pm.pkg.component;

import android.annotation.NonNull;
import android.content.pm.SignedPackageParcel;
import android.os.Parcelable;

import com.android.internal.util.DataClass;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Represents the set of rules, declared in an application's manifest via the
 * {@code <allow-component-access>} tag, that defines which other applications (and their
 * components) the application is permitted to associate with.
 *
 * @hide
 * @see R.styleable#AndroidManifestAllowComponentAccess
 */
@DataClass(genSetters = true)
public final class ParsedAllowComponentAccessPolicyImpl implements ParsedAllowComponentAccessPolicy,
        Parcelable {

    @NonNull
    private List<SignedPackageParcel> mParsedAllowlistedSignedPackages;

    @Override
    public void writeToParcel(@NonNull android.os.Parcel dest, int flags) {
        dest.writeTypedList(mParsedAllowlistedSignedPackages);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    private ParsedAllowComponentAccessPolicyImpl(@NonNull android.os.Parcel in) {
        java.util.ArrayList<SignedPackageParcel> list = in.createTypedArrayList(SignedPackageParcel.CREATOR);
        this.mParsedAllowlistedSignedPackages = Objects.requireNonNullElseGet(list, ArrayList::new);
    }

    public static final @NonNull Parcelable.Creator<ParsedAllowComponentAccessPolicyImpl> CREATOR
            = new Parcelable.Creator<ParsedAllowComponentAccessPolicyImpl>() {
        @Override
        public ParsedAllowComponentAccessPolicyImpl createFromParcel(@NonNull android.os.Parcel in) {
            return new ParsedAllowComponentAccessPolicyImpl(in);
        }

        @Override
        public ParsedAllowComponentAccessPolicyImpl[] newArray(int size) {
            return new ParsedAllowComponentAccessPolicyImpl[size];
        }
    };




    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/frameworks/base/core/java/com/android/internal/pm/pkg/component/ParsedAllowComponentAccessPolicyImpl.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    public ParsedAllowComponentAccessPolicyImpl(
            @NonNull List<SignedPackageParcel> parsedAllowlistedSignedPackages) {
        this.mParsedAllowlistedSignedPackages = parsedAllowlistedSignedPackages;
        com.android.internal.util.AnnotationValidations.validate(
                NonNull.class, null, mParsedAllowlistedSignedPackages);

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public @NonNull List<SignedPackageParcel> getParsedAllowlistedSignedPackages() {
        return mParsedAllowlistedSignedPackages;
    }

    @DataClass.Generated.Member
    public @NonNull ParsedAllowComponentAccessPolicyImpl setParsedAllowlistedSignedPackages(@NonNull List<SignedPackageParcel> value) {
        mParsedAllowlistedSignedPackages = value;
        com.android.internal.util.AnnotationValidations.validate(
                NonNull.class, null, mParsedAllowlistedSignedPackages);
        return this;
    }

    @DataClass.Generated(
            time = 1765286990783L,
            codegenVersion = "1.0.23",
            sourceFile = "frameworks/base/core/java/com/android/internal/pm/pkg/component/ParsedAllowComponentAccessPolicyImpl.java",
            inputSignatures = "private @android.annotation.NonNull java.util.List<android.content.pm.SignedPackageParcel> mParsedAllowlistedSignedPackages\npublic static final @android.annotation.NonNull android.os.Parcelable.Creator<com.android.internal.pm.pkg.component.ParsedAllowComponentAccessPolicyImpl> CREATOR\npublic @java.lang.Override void writeToParcel(android.os.Parcel,int)\npublic @java.lang.Override int describeContents()\nclass ParsedAllowComponentAccessPolicyImpl extends java.lang.Object implements [com.android.internal.pm.pkg.component.ParsedAllowComponentAccessPolicy, android.os.Parcelable]\n@com.android.internal.util.DataClass(genSetters=true)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
