/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.app.ondeviceintelligence.embedding;

import android.Manifest;
import android.annotation.FlaggedApi;
import android.annotation.NonNull;
import android.annotation.Nullable;
import android.annotation.IntDef;
import android.annotation.IntRange;
import android.annotation.RequiresPermission;
import android.annotation.SystemApi;
import android.app.ondeviceintelligence.DownloadCallback;
import android.app.ondeviceintelligence.Feature;
import android.app.ondeviceintelligence.OnDeviceIntelligenceException;
import android.app.ondeviceintelligence.OnDeviceIntelligenceManager;
import android.app.ondeviceintelligence.OnDeviceModel;
import android.app.ondeviceintelligence.FeatureDetails;
import android.app.ondeviceintelligence.flags.Flags;
import android.os.CancellationSignal;
import android.os.OutcomeReceiver;
import android.os.Parcel;
import android.os.Parcelable;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.Executor;
import java.util.stream.Collectors;

/**
 * Represents a specific on-device embedding model.
 *
 * <p>This class provides methods to query model information, check availability, download the
 * model, and perform inference to generate embeddings.
 *
 * <p>Embeddings are vector representations of data (e.g., text) that capture semantic meaning. They
 * are useful for applications such as semantic search, clustering, and similarity detection.
 *
 * @hide
 */
@SystemApi
@FlaggedApi(Flags.FLAG_ON_DEVICE_INTELLIGENCE_26Q2)
public final class EmbeddingModel implements OnDeviceModel, Parcelable {
    /** @hide */
    @IntDef(value = {MODALITY_TEXT, MODALITY_IMAGE, MODALITY_AUDIO})
    @Retention(RetentionPolicy.SOURCE)
    @Target({ElementType.TYPE_USE, ElementType.METHOD, ElementType.PARAMETER, ElementType.FIELD})
    public @interface Modality {}

    /** Text modality. */
    public static final int MODALITY_TEXT = 0;

    /** Image modality. */
    public static final int MODALITY_IMAGE = 1;

    /** Audio modality. */
    public static final int MODALITY_AUDIO = 2;

    private OnDeviceIntelligenceManager mManager;
    private final Feature mFeature;
    private final String mModelSignature;
    private final int mDimension;
    private final int[] mSupportedModalities;

    /**
     * Constructs a new {@link EmbeddingModel}.
     *
     * @param feature The internal feature.
     * @param modelSignature The signature of the model.
     * @param dimension The dimension of the embeddings.
     * @param supportedModalities The list of supported modalities.
     */
    public EmbeddingModel(
            @NonNull Feature feature,
            @NonNull String modelSignature,
            @IntRange(from = 1) int dimension,
            @NonNull List<@Modality Integer> supportedModalities) {
        mFeature = Objects.requireNonNull(feature);
        mModelSignature = Objects.requireNonNull(modelSignature);
        mDimension = dimension;
        mSupportedModalities =
                Objects.requireNonNull(supportedModalities).stream().mapToInt(i -> i).toArray();
    }

    /**
     * Sets the manager for this model.
     *
     * @hide
     */
    public void setOnDeviceIntelligenceManager(@NonNull OnDeviceIntelligenceManager manager) {
        mManager = manager;
    }

    /** Returns the unique signature of the model. */
    @Override
    @NonNull
    public String getModelSignature() {
        return mModelSignature;
    }

    /** Returns the name of the model. */
    @Override
    @NonNull
    public String getName() {
        String name = mFeature.getName();
        return name != null ? name : mModelSignature;
    }

    /** Returns the dimension of the embeddings generated by this model. */
    public int getDimension() {
        return mDimension;
    }

    /** Returns the list of supported modalities for this model. */
    @NonNull
    public List<@Modality Integer> getSupportedModalities() {
        return Arrays.stream(mSupportedModalities).boxed().collect(Collectors.toList());
    }

    /**
     * Retrieves the current status of the model.
     *
     * @param executor The executor on which to invoke the callback.
     * @param callback The callback to receive the model status (e.g., DOWNLOADABLE, AVAILABLE).
     */
    @Override
    @RequiresPermission(Manifest.permission.USE_ON_DEVICE_INTELLIGENCE)
    public void getStatus(
            @NonNull Executor executor,
            @NonNull OutcomeReceiver<Integer, OnDeviceIntelligenceException> callback) {
        Objects.requireNonNull(
                mManager, "OnDeviceIntelligenceManager instance not attached to this Model.");
        mManager.getFeatureDetails(
                mFeature,
                executor,
                new OutcomeReceiver<>() {
                    @Override
                    public void onResult(FeatureDetails result) {
                        callback.onResult(result.getFeatureStatus());
                    }

                    @Override
                    public void onError(OnDeviceIntelligenceException error) {
                        callback.onError(error);
                    }
                });
    }

    /**
     * Requests the download of the files associated with this model.
     *
     * @param signal A {@link CancellationSignal} to cancel the download operation.
     * @param executor The executor on which to invoke the callback.
     * @param callback The callback to receive download progress and status updates.
     */
    @Override
    @RequiresPermission(Manifest.permission.USE_ON_DEVICE_INTELLIGENCE)
    public void download(
            @Nullable CancellationSignal signal,
            @NonNull Executor executor,
            @NonNull DownloadCallback callback) {
        Objects.requireNonNull(
                mManager, "OnDeviceIntelligenceManager instance not attached to this Model.");
        mManager.requestFeatureDownload(mFeature, signal, executor, callback);
    }

    /**
     * Generates embeddings for the provided text.
     *
     * @param text The text input to generate embeddings for.
     * @param signal A {@link CancellationSignal} to cancel the operation.
     * @param executor The executor on which to invoke the callback.
     * @param callback The callback to receive the generated {@link EmbeddingResponse} or an error.
     */
    @RequiresPermission(Manifest.permission.USE_ON_DEVICE_INTELLIGENCE)
    public void generateEmbeddings(
            @NonNull String text,
            @Nullable CancellationSignal signal,
            @NonNull Executor executor,
            @NonNull OutcomeReceiver<EmbeddingResponse, OnDeviceIntelligenceException> callback) {
        Objects.requireNonNull(
                mManager, "OnDeviceIntelligenceManager instance not attached to this Model.");
        EmbeddingRequest request = new EmbeddingRequest(text);
        mManager.generateEmbeddings(mFeature, request, signal, executor, callback);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(@NonNull Parcel dest, int flags) {
        dest.writeTypedObject(mFeature, flags);
        dest.writeString8(mModelSignature);
        dest.writeInt(mDimension);
        dest.writeIntArray(mSupportedModalities);
    }

    public static final @NonNull Creator<EmbeddingModel> CREATOR =
            new Creator<EmbeddingModel>() {
                @Override
                public EmbeddingModel createFromParcel(Parcel in) {
                    return new EmbeddingModel(in);
                }

                @Override
                public EmbeddingModel[] newArray(int size) {
                    return new EmbeddingModel[size];
                }
            };

    private EmbeddingModel(Parcel in) {
        mFeature = in.readTypedObject(Feature.CREATOR);
        mModelSignature = in.readString8();
        mDimension = in.readInt();
        mSupportedModalities = in.createIntArray();
    }
}
