/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.service.personalcontext.refiner;

import android.annotation.FlaggedApi;
import android.annotation.Nullable;
import android.annotation.SystemApi;
import android.app.Service;
import android.content.Intent;
import android.os.Bundle;
import android.os.IBinder;
import android.os.ParcelUuid;
import android.os.RemoteException;
import android.service.personalcontext.Flags;
import android.service.personalcontext.hint.ContextHint;
import android.service.personalcontext.hint.ContextHintWithSignature;
import android.service.personalcontext.hint.ContextHintWithSignatureWrapper;
import android.service.personalcontext.hint.ContextHintWrapper;
import android.service.personalcontext.hint.HintFilter;
import android.service.personalcontext.insight.ContextInsightWrapper;
import android.service.personalcontext.insight.interaction.InsightEvent;
import android.util.Log;

import androidx.annotation.NonNull;

import java.lang.ref.WeakReference;
import java.util.List;
import java.util.UUID;
import java.util.function.Consumer;

/**
 * This is the base class for refiner services to implement, handling service details.
 *
 * <p>A refiner provides more information to the Personal Context system by adding
 * {@link ContextHint}s. These hints can be created with no basis on existing hints (e.g. a
 * device screenshot), or they can be derived from other hints (e.g. OCR text from a screenshot).
 * Generated hints will be forwarded to understanding components to be analyzed, and to other
 * refiners that may be interested in them.
 *
 * <p>A refiner receives incoming hints based on the filter specified in
 * {@link #onInitializeFilter()}. While a refiner only processes a particular {@link ContextHint}
 * once, it may encounter {@link ContextHint} derived by another refiner from a previously seen
 * {@link ContextHint} if it matches the filter as well.
 *
 * <p>The Personal Context service will manage the lifetime of this service, and this service may be
 * stopped if not utilized for some time. Services should start as rapidly as possible to minimize
 * latency in the Personal Context workflow.
 *
 * @hide
 */
@SystemApi
@FlaggedApi(Flags.FLAG_ENABLE_PERSONAL_CONTEXT_SERVICE)
public abstract class HintRefinerService extends Service {
    private static final String TAG = "HintRefinerService";

    private UUID mComponentId = null;

    /** @hide */
    @NonNull
    public final UUID getComponentId() {
        if (mComponentId == null) {
            throw new IllegalStateException("Service has not been configured yet");
        }
        return mComponentId;
    }

    @Override
    @Nullable
    public final IBinder onBind(@Nullable Intent intent) {
        return new Binder(this);
    }

    private void configure(UUID componentId) {
        mComponentId = componentId;
        onConnected();
    }

    /** Called when the refiner has been configured and is ready to receive hints. */
    public void onConnected() {
        // Default implementation does nothing.
    }

    /**
     * The refiner must return a {@link HintFilter} that will be used to filter the hints
     * that this refiner's {@link #onRefine} method will be called with.
     *
     * The result of this method will be cached and re-used between service bindings. If the filter
     * returned by this method changes, the changes will be ignored.
     *
     * @return a filter that restricts the {@link ContextHint}s this refiner will receive
     */
    @NonNull
    public abstract HintFilter onInitializeFilter();

    /**
     * Called when there are hints to be generated or refined.
     *
     * <p>Use the callback to provide new hints to the Personal Context system. Do *not* use
     * {@link PersonalContextManager#publishTriggeringHint} to provide new hints from a refiner;
     * providing hints this way will cause hints to not be attributed properly and will break some
     * rendering flows.
     *
     * <p>Refiners should not cache hints between calls. The callback may only be
     * called once, and should be called with only new hints generated by this refiner. Repeated
     * calls and hints that have been delivered before will be ignored.
     *
     * @param inputHints set of hints that this refiner may want to use to derive new hints
     * @param callback provides new hints back to the system
     */
    public abstract void onRefine(
            @NonNull List<ContextHint> inputHints,
            @NonNull Consumer<List<ContextHint>> callback);

    private static final class Binder extends IRefiner.Stub {
        private final WeakReference<HintRefinerService> mService;

        private Binder(HintRefinerService service) {
            mService = new WeakReference<>(service);
        }

        private HintRefinerService getServiceOrThrow() throws RemoteException {
            final HintRefinerService service = mService.get();
            if (service == null) {
                Log.e(TAG, "Service is no longer available");
                throw new RemoteException("Service is no longer available");
            } else {
                return service;
            }
        }

        @Override
        public void configure(ParcelUuid componentId) throws RemoteException {
            getServiceOrThrow().configure(componentId.getUuid());
        }

        @Override
        public void refine(
                List<ContextHintWithSignatureWrapper> inputHints, IRefineCallback callback)
                throws RemoteException {
            getServiceOrThrow().onRefine(
                    ContextHintWithSignature.unwrapList(
                            ContextHintWithSignatureWrapper.unwrapList(inputHints)),
                    hints -> {
                        try {
                            callback.onHintsRefined(ContextHintWrapper.wrapList(hints));
                        } catch (RemoteException e) {
                            Log.i(TAG, "Could not return refined hints", e);
                        }
                    });
        }

        @Override
        public void getFilter(IGetFilterCallback callback) throws RemoteException {
            callback.updateFilter(getServiceOrThrow().onInitializeFilter());
        }

        @Override
        public void handleEvent(String packageName, InsightEvent event) {
            throw new UnsupportedOperationException("Can not handle insight events in a refiner");
        }

        @Override
        public void handleFeedback(ContextInsightWrapper insight, Bundle feedback) {
            throw new UnsupportedOperationException("Can not handle user feedback in a refiner");
        }
    }
}
